//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CultureCompass.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CultureCompass.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CultureCompass.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a route to follow and start navigating! The app will display a map with the selected route, your live location and the distance to the next waypoint. When entering in the vicinity of a waypoint on the route, a notification is triggered to inform you. During navigation you will be able to stop the route and return to the menu..
        /// </summary>
        internal static string AppUsage {
            get {
                return ResourceManager.GetString("AppUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App usage.
        /// </summary>
        internal static string AppUsageHeader {
            get {
                return ResourceManager.GetString("AppUsageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time left to next waypoint: .
        /// </summary>
        internal static string DurationPrefix {
            get {
                return ResourceManager.GetString("DurationPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance left to next waypoint: .
        /// </summary>
        internal static string NavigationNextWaypointDistancePrefix {
            get {
                return ResourceManager.GetString("NavigationNextWaypointDistancePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Route.
        /// </summary>
        internal static string RouteStart {
            get {
                return ResourceManager.GetString("RouteStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Route.
        /// </summary>
        internal static string RouteStop {
            get {
                return ResourceManager.GetString("RouteStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each route consists of a number of waypoints, indicated on the route selection page. You may tap the icon of a waypoint to display more information about it..
        /// </summary>
        internal static string RouteUsage {
            get {
                return ResourceManager.GetString("RouteUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route info.
        /// </summary>
        internal static string RouteUsageHeader {
            get {
                return ResourceManager.GetString("RouteUsageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of waypoints: .
        /// </summary>
        internal static string RouteWaypointAmountPrefix {
            get {
                return ResourceManager.GetString("RouteWaypointAmountPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build year: .
        /// </summary>
        internal static string WaypointBuildYearHeader {
            get {
                return ResourceManager.GetString("WaypointBuildYearHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string WaypointBuildYearPlaceholder {
            get {
                return ResourceManager.GetString("WaypointBuildYearPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string WaypointDescriptionHeader {
            get {
                return ResourceManager.GetString("WaypointDescriptionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string WaypointDescriptionPlaceholder {
            get {
                return ResourceManager.GetString("WaypointDescriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to route.
        /// </summary>
        internal static string WaypointReturn {
            get {
                return ResourceManager.GetString("WaypointReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
